<?php

namespace App\Repository;

/**
 * GroupImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    /**
     * getCategories
     *
     * @param  null
     * @return array
     */
    public function getCategories() {
                
        $em = $this->getEntityManager();
        $RAW_QUERY = "SELECT c.* FROM bookshop_category AS c";
        $statement = $em->getConnection()->prepare($RAW_QUERY);
        $statement->execute();
        
        return $statement->fetchAll();
        
       
    }
    
    
    /**
     * getCategoryByName
     *
     * @param string $category
     * @return array
     */
    public function getCategoryByName($category) {
                
        $em = $this->getEntityManager();
        $RAW_QUERY = "SELECT c.* FROM bookshop_category AS c WHERE c.name LIKE :category";
        $statement = $em->getConnection()->prepare($RAW_QUERY);
        $statement->execute(array("category" => "%".$category."%"));
        
        return $statement->fetch();
        
       
    }
    
    
}
